export type {
  AutoFillCandidate,
  AutoFillPreview,
  AutoFillRequest,
  Orientation,
  PanelDefinition,
  PanelFootprint,
  PanelGroupSettings,
  PanelPlacement,
  Point2,
  Point3,
  Polygon,
  Rect,
  RectangularObstacle,
  SurfaceDescriptor,
  SurfaceEdge,
  SurfaceEdgeLine,
  SurfaceEdgeMetadata,
  SurfaceEdgeSide,
  SurfaceEdgeType,
  SurfaceFaceRef,
  SurfaceFrame,
  SurfaceNormal,
  SurfaceRegion,
  SurfaceSelection,
} from './types'

export { DEFAULT_PANEL_GROUP_SETTINGS, SURFACE_EDGE_DIRECTION_EPSILON } from './types'

export {
  assertFiniteNumber,
  createAutoFillCandidate,
  createAutoFillPreview,
  createAutoFillRequest,
  createPanelDefinition,
  createPanelFootprint,
  createPanelGroupSettings,
  createPanelPlacement,
  createPoint2,
  createPoint3,
  createPolygon,
  createRect,
  createRectangularObstacle,
  createSurfaceEdge,
  createSurfaceEdgeMetadata,
  createSurfaceDescriptor,
  createSurfaceFaceRef,
  createSurfaceFrame,
  createSurfaceNormal,
  createSurfaceRegion,
  createSurfaceSelection,
  deepFreeze,
  isAutoFillCandidate,
  isAutoFillPreview,
  isAutoFillRequest,
  isFiniteNumber,
  isOrientation,
  isPanelDefinition,
  isPanelFootprint,
  isPanelGroupSettings,
  isPanelPlacement,
  isPoint2,
  isPoint3,
  isPolygon,
  isRect,
  isRectangularObstacle,
  isSurfaceDescriptor,
  isSurfaceEdge,
  isSurfaceEdgeLine,
  isSurfaceEdgeMetadata,
  isSurfaceEdgeSide,
  isSurfaceEdgeType,
  isSurfaceFaceRef,
  isSurfaceFrame,
  isSurfaceNormal,
  isSurfaceRegion,
  isSurfaceSelection,
} from './validation'

export type { FrameCoordinates } from './frame'
export {
  pointFromSurfaceCoordinates,
  projectPointToFrame,
  projectPointToSurface,
  unprojectPointFromFrame,
} from './frame'
