#!/usr/bin/env python3
"""Generate and validate the deterministic PV Studio WebODM-style fixture.

The real ODMData catalogue publishes the aerial source photographs and asks
users to run ODM locally; it does not publish a small, redistributable OBJ
bundle.  This fixture therefore keeps the same output contract (OBJ + MTL +
JPEG texture maps) while remaining reproducible and easy to load from the
browser.  Geometry is a lightly noisy house/roof/ground scene, rather than a
placeholder cube, so surface picking and roof placement can be exercised.

Usage:
    python3 scripts/generate-webodm-sample.py
    python3 scripts/generate-webodm-sample.py --validate

The generator intentionally has no third-party Python dependencies.  JPEG
maps are produced through ffmpeg when available and a tiny valid fallback map
is emitted when it is not; the checked-in fixture is generated with ffmpeg.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import math
import random
import re
import shutil
import struct
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "public" / "test-data" / "synthetic-webodm-house"
OBJ_PATH = OUTPUT / "synthetic-webodm-house.obj"
MTL_PATH = OUTPUT / "synthetic-webodm-house.mtl"
TEXTURES = (OUTPUT / "ground-texture.jpg", OUTPUT / "roof-texture.jpg", OUTPUT / "wall-texture.jpg")

EXPECTED_COUNTS = (545_871, 545_871, 7, 1_086_560)
REQUIRED_MATERIAL_TEXTURES = {
    "Ground": "ground-texture.jpg",
    "Roof": "roof-texture.jpg",
    "Wall": "wall-texture.jpg",
}
EXPECTED_GROUP_FACES = {
    "Ground": 980_000,
    "RoofNorth": 36_000,
    "RoofSouth": 36_000,
    "WallEast": 8_640,
    "WallWest": 8_640,
    "WallNorth": 8_640,
    "WallSouth": 8_640,
}
EXPECTED_GROUP_MATERIALS = {
    "Ground": "Ground",
    "RoofNorth": "Roof",
    "RoofSouth": "Roof",
    "WallEast": "Wall",
    "WallWest": "Wall",
    "WallNorth": "Wall",
    "WallSouth": "Wall",
}

# Canonical SHA-256 values for the checked-in outputs generated by this script.
# Integrity checks are deliberately independent of Pillow/ffmpeg so a JPEG with
# a plausible marker stream but corrupted entropy bytes cannot pass validation.
EXPECTED_ARTIFACT_SHA256 = {
    "synthetic-webodm-house.obj": "3934211d4e983dd855c6458e99dbaf3f7b2283510de1b469117598f050cfd196",
    "synthetic-webodm-house.mtl": "767005ac4294e70aee9e32306280d0d1c5fc11d09af46d6f22798ab017fddf5b",
    "ground-texture.jpg": "7ab85a4c63794f3e2bfb1aa3c4552a90b788eb2a241ee6f9829b5cf0073eb96f",
    "roof-texture.jpg": "59e76a17281ffe0b274ade53b343c3012b77434317d9d3e044bfc6e212d8764b",
    "wall-texture.jpg": "fbcd096f5ffdce4e3eec2dce9fe4e5e24022c0bc30eb509c235daad7c8d5f112",
}

# A deterministic 1x1 JPEG used only if ffmpeg is unavailable on a developer
# machine.  It is a real JPEG (not a renamed PNG/PPM) and keeps the fixture
# usable in minimal CI images.
FALLBACK_JPEG = base64.b64decode(
    """
/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////
2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAH/AP/EABQQAQAAAAAAAAAAAAAAAAAAACD/2gAIAQEAAQUCf//EABQRAQAAAAAAAAAAAAAAAAAAACD/2gAIAQMBAT8Bf//EABQRAQAAAAAAAAAAAAAAAAAAACD/2gAIAQIBAT8Bf//EABQQAQAAAAAAAAAAAAAAAAAAACD/2gAIAQEABj8Cf//Z
""".replace("\n", "")
)


@dataclass(frozen=True)
class Surface:
    name: str
    material: str
    normal: tuple[float, float, float]
    vertices: tuple[tuple[float, float, float], ...]
    uvs: tuple[tuple[float, float], ...]
    width: int
    height: int


def noise(x: float, z: float, scale: float = 1.0) -> float:
    """Stable low-amplitude terrain/photogrammetry noise."""

    return scale * (
        math.sin(x * 0.73 + z * 0.17)
        + math.cos(x * 0.11 - z * 0.61)
        + math.sin((x + z) * 0.31)
    ) / 3.0


def grid_surface(
    name: str,
    material: str,
    width: int,
    height: int,
    point: callable,
    normal: tuple[float, float, float],
    uv_scale: tuple[float, float] = (1.0, 1.0),
) -> Surface:
    """Create a rectangular indexed grid, retaining a predictable topology."""

    vertices: list[tuple[float, float, float]] = []
    uvs: list[tuple[float, float]] = []
    for row in range(height + 1):
        v = row / height
        for column in range(width + 1):
            u = column / width
            vertices.append(point(u, v))
            uvs.append((u * uv_scale[0], v * uv_scale[1]))
    return Surface(name, material, normal, tuple(vertices), tuple(uvs), width, height)


def build_surfaces() -> tuple[Surface, ...]:
    """Build the pitched-roof house, four walls, and textured ground."""

    # 700 x 700 cells gives 980,000 ground triangles. Combined with roofs and
    # walls this clears the current 500,000-polygon large-model acceptance
    # target while keeping the OBJ comfortably below GitHub's 100 MiB limit.
    # The stable seed is intentionally explicit for repeatable validation and
    # review.
    random.seed(20260809)
    ground_width = 700
    ground_height = 700
    ground = grid_surface(
        "Ground",
        "Ground",
        ground_width,
        ground_height,
        lambda u, v: (
            -25.0 + u * 50.0,
            noise(-25.0 + u * 50.0, -20.0 + v * 40.0, 0.07),
            -20.0 + v * 40.0,
        ),
        (0.0, 1.0, 0.0),
        (12.0, 10.0),
    )

    roof_width = 180
    roof_half_height = 100
    house_x_min, house_x_max = -12.0, 12.0
    eave_z, ridge_z = 8.0, 0.0
    eave_y, ridge_y = 3.8, 7.4

    north_roof = grid_surface(
        "RoofNorth",
        "Roof",
        roof_width,
        roof_half_height,
        lambda u, v: (
            house_x_min + u * (house_x_max - house_x_min),
            ridge_y + v * (eave_y - ridge_y) + noise(u * 24.0, v * 8.0, 0.012),
            ridge_z + v * (eave_z - ridge_z),
        ),
        (0.0, 0.91, 0.43),
        (8.0, 3.0),
    )
    south_roof = grid_surface(
        "RoofSouth",
        "Roof",
        roof_width,
        roof_half_height,
        lambda u, v: (
            house_x_min + u * (house_x_max - house_x_min),
            ridge_y + v * (eave_y - ridge_y) + noise(u * 24.0, v * 8.0, 0.012),
            ridge_z - v * (eave_z - ridge_z),
        ),
        (0.0, 0.91, -0.43),
        (8.0, 3.0),
    )

    wall_width = 120
    wall_height = 36
    walls = (
        grid_surface(
            "WallEast",
            "Wall",
            wall_width,
            wall_height,
            lambda u, v: (
                house_x_max,
                v * eave_y + noise(u * 20.0, v * 5.0, 0.008),
                -eave_z + u * 2.0 * eave_z,
            ),
            (1.0, 0.0, 0.0),
            (6.0, 2.0),
        ),
        grid_surface(
            "WallWest",
            "Wall",
            wall_width,
            wall_height,
            lambda u, v: (
                house_x_min,
                v * eave_y + noise(u * 20.0, v * 5.0, 0.008),
                eave_z - u * 2.0 * eave_z,
            ),
            (-1.0, 0.0, 0.0),
            (6.0, 2.0),
        ),
        grid_surface(
            "WallNorth",
            "Wall",
            wall_width,
            wall_height,
            lambda u, v: (
                house_x_min + u * (house_x_max - house_x_min),
                v * eave_y + noise(u * 20.0, v * 5.0, 0.008),
                eave_z,
            ),
            (0.0, 0.0, 1.0),
            (6.0, 2.0),
        ),
        grid_surface(
            "WallSouth",
            "Wall",
            wall_width,
            wall_height,
            lambda u, v: (
                house_x_max - u * (house_x_max - house_x_min),
                v * eave_y + noise(u * 20.0, v * 5.0, 0.008),
                -eave_z,
            ),
            (0.0, 0.0, -1.0),
            (6.0, 2.0),
        ),
    )
    return (ground, north_roof, south_roof, *walls)


def write_obj(surfaces: tuple[Surface, ...]) -> tuple[int, int, int, int]:
    """Write OBJ and return (vertices, texcoords, normals, triangles)."""

    vertices: list[tuple[float, float, float]] = []
    texcoords: list[tuple[float, float]] = []
    normals: list[tuple[float, float, float]] = []
    # Each surface uses one normal, which mirrors common ODM material chunks
    # while avoiding redundant normal records in this reproducible fixture.
    vertex_ranges: list[tuple[int, int, int]] = []
    for surface in surfaces:
        vertex_start = len(vertices) + 1
        uv_start = len(texcoords) + 1
        vertices.extend(surface.vertices)
        texcoords.extend(surface.uvs)
        normals.append(surface.normal)
        vertex_ranges.append((vertex_start, uv_start, len(normals)))

    OUTPUT.mkdir(parents=True, exist_ok=True)
    with OBJ_PATH.open("w", encoding="utf-8", newline="\n") as obj:
        obj.write("# PV Studio deterministic synthetic WebODM fixture\n")
        obj.write("# Geometry: pitched-roof house, walls, and lightly noisy ground\n")
        obj.write("# Source/provenance: generated in-repo; no third-party assets\n")
        obj.write("mtllib synthetic-webodm-house.mtl\n")
        obj.write("o SyntheticPhotogrammetryHouse\n")
        for x, y, z in vertices:
            obj.write(f"v {x:.5f} {y:.5f} {z:.5f}\n")
        for u, v in texcoords:
            obj.write(f"vt {u:.5f} {v:.5f}\n")
        for x, y, z in normals:
            obj.write(f"vn {x:.5f} {y:.5f} {z:.5f}\n")

        triangles = 0
        for surface, (vertex_start, uv_start, normal_index) in zip(surfaces, vertex_ranges):
            obj.write(f"g {surface.name}\n")
            obj.write(f"usemtl {surface.material}\n")
            row_stride = surface.width + 1
            for row in range(surface.height):
                for column in range(surface.width):
                    a = row * row_stride + column
                    b = a + 1
                    c = a + row_stride
                    d = c + 1
                    va, vb, vc, vd = (vertex_start + a, vertex_start + b, vertex_start + c, vertex_start + d)
                    ua, ub, uc, ud = (uv_start + a, uv_start + b, uv_start + c, uv_start + d)
                    # a-c-b and b-c-d wind upwards for the horizontal ground;
                    # all other surfaces are double-sided in the application,
                    # but retain deterministic winding for normal-aware tools.
                    if surface.name == "Ground":
                        faces = (((va, ua), (vc, uc), (vb, ub)), ((vb, ub), (vc, uc), (vd, ud)))
                    else:
                        faces = (((va, ua), (vb, ub), (vc, uc)), ((vb, ub), (vd, ud), (vc, uc)))
                    for (first, first_uv), (second, second_uv), (third, third_uv) in faces:
                        obj.write(
                            f"f {first}/{first_uv}/{normal_index} "
                            f"{second}/{second_uv}/{normal_index} "
                            f"{third}/{third_uv}/{normal_index}\n"
                        )
                        triangles += 1

    mtl = """# PV Studio deterministic synthetic WebODM fixture\n# Materials are intentionally simple and map to local JPEG textures.\nnewmtl Ground\nKa 0.25 0.29 0.20\nKd 0.42 0.48 0.32\nKs 0.05 0.05 0.05\nNs 8.0\nmap_Kd ground-texture.jpg\n\nnewmtl Roof\nKa 0.18 0.20 0.22\nKd 0.34 0.39 0.45\nKs 0.12 0.12 0.12\nNs 24.0\nmap_Kd roof-texture.jpg\n\nnewmtl Wall\nKa 0.45 0.38 0.30\nKd 0.72 0.61 0.46\nKs 0.05 0.05 0.05\nNs 8.0\nmap_Kd wall-texture.jpg\n"""
    MTL_PATH.write_text(mtl, encoding="utf-8", newline="\n")
    return len(vertices), len(texcoords), len(normals), triangles


def write_texture(path: Path, colour: tuple[int, int, int], seed: int) -> None:
    """Write a deterministic noise PPM and encode it as a JPEG through ffmpeg."""

    ffmpeg = shutil.which("ffmpeg")
    if ffmpeg is None:
        path.write_bytes(FALLBACK_JPEG)
        return
    width, height = 512, 512
    rng = random.Random(seed)
    with tempfile.TemporaryDirectory(prefix="pvstudio-texture-") as temp_dir:
        ppm_path = Path(temp_dir) / "texture.ppm"
        with ppm_path.open("wb") as ppm:
            ppm.write(f"P6\n{width} {height}\n255\n".encode("ascii"))
            for y in range(height):
                for x in range(width):
                    grain = rng.randrange(-16, 17)
                    stripe = int(11 * math.sin(x / 19.0) + 7 * math.cos(y / 31.0))
                    pixel = bytes(max(0, min(255, channel + grain + stripe)) for channel in colour)
                    ppm.write(pixel)
        subprocess.run(
            [ffmpeg, "-hide_banner", "-loglevel", "error", "-y", "-i", str(ppm_path), "-q:v", "3", "-threads", "1", str(path)],
            check=True,
        )


def generate() -> tuple[int, int, int, int]:
    surfaces = build_surfaces()
    stats = write_obj(surfaces)
    write_texture(TEXTURES[0], (99, 121, 66), 11)
    write_texture(TEXTURES[1], (79, 95, 112), 22)
    write_texture(TEXTURES[2], (173, 143, 103), 33)
    return stats


@dataclass
class GroupStats:
    """Bounds and winding evidence collected while validating one OBJ group."""

    name: str
    material: str | None = None
    faces: int = 0
    min_x: float = math.inf
    max_x: float = -math.inf
    min_y: float = math.inf
    max_y: float = -math.inf
    min_z: float = math.inf
    max_z: float = -math.inf
    first_centroid: tuple[float, float, float] | None = None
    last_centroid: tuple[float, float, float] | None = None

    def update(self, triangle: tuple[tuple[float, float, float], ...]) -> None:
        """Record a triangle; all area/index checks happen before this call."""

        self.faces += 1
        for x, y, z in triangle:
            self.min_x = min(self.min_x, x)
            self.max_x = max(self.max_x, x)
            self.min_y = min(self.min_y, y)
            self.max_y = max(self.max_y, y)
            self.min_z = min(self.min_z, z)
            self.max_z = max(self.max_z, z)
        centroid = tuple(sum(vertex[index] for vertex in triangle) / 3.0 for index in range(3))
        if self.first_centroid is None:
            self.first_centroid = centroid
        self.last_centroid = centroid

    @property
    def x_extent(self) -> float:
        return self.max_x - self.min_x

    @property
    def y_extent(self) -> float:
        return self.max_y - self.min_y

    @property
    def z_extent(self) -> float:
        return self.max_z - self.min_z


def fixture_paths(root: Path = OUTPUT) -> tuple[Path, Path, dict[str, Path]]:
    """Resolve fixture files below ``root`` (used by validation tests)."""

    fixture_root = root.resolve()
    return (
        fixture_root / OBJ_PATH.name,
        fixture_root / MTL_PATH.name,
        {material: fixture_root / filename for material, filename in REQUIRED_MATERIAL_TEXTURES.items()},
    )


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _validate_artifact_hash(path: Path, expected: str) -> None:
    actual = _sha256(path)
    if actual != expected:
        raise ValueError(f"Canonical artifact hash mismatch for {path.name}: {actual} != {expected}")


def parse_mtl(path: Path) -> dict[str, dict[str, str]]:
    """Parse material blocks and preserve their map_Kd references."""

    materials: dict[str, dict[str, str]] = {}
    current: str | None = None
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        keyword, separator, value = line.partition(" ")
        value = value.strip() if separator else ""
        if keyword == "newmtl":
            if not value or value in materials:
                raise ValueError(f"Invalid or duplicate newmtl at {path}:{line_number}")
            current = value
            materials[current] = {}
        elif keyword == "map_Kd":
            if current is None or not value:
                raise ValueError(f"map_Kd appears outside a material block at {path}:{line_number}")
            if "map_Kd" in materials[current]:
                raise ValueError(f"Duplicate map_Kd for {current} at {path}:{line_number}")
            materials[current]["map_Kd"] = value
    if not materials:
        raise ValueError(f"MTL contains no material blocks: {path}")
    return materials


WINDOWS_ABSOLUTE = re.compile(r"^(?:[A-Za-z]:[\\/]|//)")


def resolve_texture_reference(
    reference: str,
    root: Path,
    expected_name: str | None = None,
) -> Path:
    """Resolve a map_Kd path safely beneath the fixture root and validate it."""

    value = reference.strip()
    normalized = value.replace("\\", "/")
    if not value or "\x00" in value or normalized.startswith("/") or WINDOWS_ABSOLUTE.match(normalized):
        raise ValueError(f"Unsafe absolute/empty texture reference: {reference!r}")
    relative = PurePosixPath(normalized)
    if relative.is_absolute() or any(part == ".." for part in relative.parts):
        raise ValueError(f"Texture reference escapes fixture root: {reference!r}")
    root_resolved = root.resolve()
    candidate = (root_resolved.joinpath(*relative.parts)).resolve()
    try:
        candidate.relative_to(root_resolved)
    except ValueError as error:
        raise ValueError(f"Texture reference escapes fixture root: {reference!r}") from error
    if candidate.suffix.lower() not in {".jpg", ".jpeg"}:
        raise ValueError(f"Texture reference is not a JPEG: {reference!r}")
    if expected_name is not None:
        expected_path = (root_resolved / expected_name).resolve()
        if candidate != expected_path:
            raise ValueError(f"{expected_name} material must map to {expected_name}, got {reference!r}")
    if not candidate.is_file():
        raise ValueError(f"Texture file does not exist: {reference!r}")
    jpeg_dimensions(candidate)
    return candidate


JPEG_STANDALONE_MARKERS = {0x01, 0xD8, 0xD9, *range(0xD0, 0xD8)}
JPEG_SOF_MARKERS = {
    0xC0,
    0xC1,
    0xC2,
    0xC3,
    0xC5,
    0xC6,
    0xC7,
    0xC9,
    0xCA,
    0xCB,
    0xCD,
    0xCE,
    0xCF,
}


def jpeg_dimensions(path: Path) -> tuple[int, int]:
    """Parse a complete JPEG stream and return (width, height).

    This intentionally uses a marker/entropy parser instead of only searching
    for an SOF marker: a truncated scan, malformed segment length, missing EOI,
    or trailing garbage must not be accepted as a usable texture.
    """

    data = path.read_bytes()
    if len(data) < 4 or data[:2] != b"\xff\xd8":
        raise ValueError(f"{path.name} is not a JPEG (missing SOI)")
    index = 2
    width: int | None = None
    height: int | None = None
    saw_sos = False

    def segment_end(marker: int, start: int) -> int:
        if start + 2 > len(data):
            raise ValueError(f"{path.name} has a truncated {marker:02X} segment length")
        segment_length = struct.unpack(">H", data[start:start + 2])[0]
        if segment_length < 2:
            raise ValueError(f"{path.name} has an invalid {marker:02X} segment length")
        end = start + segment_length
        if end > len(data):
            raise ValueError(f"{path.name} has a truncated {marker:02X} segment")
        return end

    while index < len(data):
        if data[index] != 0xFF:
            raise ValueError(f"{path.name} has bytes outside a JPEG marker/scan")
        while index < len(data) and data[index] == 0xFF:
            index += 1
        if index >= len(data):
            raise ValueError(f"{path.name} is truncated before its EOI marker")
        marker = data[index]
        index += 1
        if marker == 0x00:
            raise ValueError(f"{path.name} contains an unexpected stuffed marker")
        if marker == 0xD9:
            if not saw_sos or width is None or height is None:
                raise ValueError(f"{path.name} has EOI before a complete image scan")
            if index != len(data):
                raise ValueError(f"{path.name} contains trailing bytes after EOI")
            return width, height
        if marker == 0xDA:
            end = segment_end(marker, index)
            if end - index < 8:
                raise ValueError(f"{path.name} has a malformed SOS segment")
            saw_sos = True
            index = end
            scan_data = False
            while index < len(data):
                if data[index] != 0xFF:
                    scan_data = True
                    index += 1
                    continue
                marker_start = index
                marker_index = index + 1
                while marker_index < len(data) and data[marker_index] == 0xFF:
                    marker_index += 1
                if marker_index >= len(data):
                    raise ValueError(f"{path.name} is truncated in entropy-coded scan")
                scan_marker = data[marker_index]
                if scan_marker == 0x00 or 0xD0 <= scan_marker <= 0xD7:
                    scan_data = True
                    index = marker_index + 1
                    continue
                if not scan_data:
                    raise ValueError(f"{path.name} has an empty entropy-coded scan")
                index = marker_start
                break
            else:
                raise ValueError(f"{path.name} is truncated before its EOI marker")
            continue
        if marker in JPEG_STANDALONE_MARKERS:
            continue
        segment_start = index
        segment_end_index = segment_end(marker, segment_start)
        if marker in JPEG_SOF_MARKERS:
            if segment_end_index - segment_start < 8:
                raise ValueError(f"{path.name} has a malformed SOF{marker:02X} segment")
            height, width = struct.unpack(">HH", data[segment_start + 3:segment_start + 7])
            if width < 1 or height < 1:
                raise ValueError(f"{path.name} has invalid dimensions {width}x{height}")
        index = segment_end_index
    raise ValueError(f"{path.name} is missing its EOI marker")


def _parse_float(value: str, path: Path, line_number: int) -> float:
    try:
        number = float(value)
    except ValueError as error:
        raise ValueError(f"Invalid numeric coordinate at {path}:{line_number}") from error
    if not math.isfinite(number):
        raise ValueError(f"Non-finite coordinate at {path}:{line_number}")
    return number


def _triangle_area_squared(triangle: tuple[tuple[float, float, float], ...]) -> float:
    (ax, ay, az), (bx, by, bz), (cx, cy, cz) = triangle
    ab = (bx - ax, by - ay, bz - az)
    ac = (cx - ax, cy - ay, cz - az)
    cross = (
        ab[1] * ac[2] - ab[2] * ac[1],
        ab[2] * ac[0] - ab[0] * ac[2],
        ab[0] * ac[1] - ab[1] * ac[0],
    )
    return sum(component * component for component in cross)


def _validate_group_shapes(groups: dict[str, GroupStats]) -> None:
    if set(groups) != set(EXPECTED_GROUP_FACES):
        raise ValueError(f"Unexpected OBJ groups: {sorted(groups)}")
    for name, expected_faces in EXPECTED_GROUP_FACES.items():
        group = groups[name]
        if group.faces != expected_faces:
            raise ValueError(f"{name} has {group.faces} faces; expected {expected_faces}")
        if group.first_centroid is None or group.last_centroid is None:
            raise ValueError(f"{name} has no geometry")

    ground = groups["Ground"]
    if not (ground.x_extent >= 45.0 and ground.z_extent >= 35.0 and 0.05 < ground.y_extent < 0.5):
        raise ValueError("Ground does not span a credible broad, nearly level surface")
    if not (ground.min_y < 0.0 < ground.max_y):
        raise ValueError("Ground elevation range is not centred around zero")

    roof_north = groups["RoofNorth"]
    roof_south = groups["RoofSouth"]
    for roof in (roof_north, roof_south):
        if not (roof.x_extent >= 20.0 and roof.z_extent >= 7.0 and roof.y_extent >= 3.0):
            raise ValueError(f"{roof.name} does not have a pitched-roof footprint")
        if not (3.0 < roof.min_y < 4.5 and 6.5 < roof.max_y < 8.5):
            raise ValueError(f"{roof.name} elevation range is not credible")
    north_delta = tuple(b - a for a, b in zip(roof_north.first_centroid, roof_north.last_centroid))
    south_delta = tuple(b - a for a, b in zip(roof_south.first_centroid, roof_south.last_centroid))
    if abs(north_delta[2]) <= 1.0e-9 or abs(south_delta[2]) <= 1.0e-9:
        raise ValueError("Roof groups do not span a ridge-to-eave direction")
    north_slope = north_delta[1] / north_delta[2]
    south_slope = south_delta[1] / south_delta[2]
    if not (north_delta[2] > 6.0 and north_slope < -0.2):
        raise ValueError("RoofNorth does not descend toward its eave")
    if not (south_delta[2] < -6.0 and south_slope > 0.2):
        raise ValueError("RoofSouth does not descend toward its eave")

    for name in ("WallEast", "WallWest"):
        wall = groups[name]
        if not (wall.x_extent < 0.25 and wall.z_extent >= 14.0 and wall.y_extent >= 3.0):
            raise ValueError(f"{name} is not a vertical side wall")
        if not (-0.5 < wall.min_y < 0.5 and 3.0 < wall.max_y < 4.5):
            raise ValueError(f"{name} elevation range is not credible")
    for name in ("WallNorth", "WallSouth"):
        wall = groups[name]
        if not (wall.z_extent < 0.25 and wall.x_extent >= 20.0 and wall.y_extent >= 3.0):
            raise ValueError(f"{name} is not a vertical end wall")
        if not (-0.5 < wall.min_y < 0.5 and 3.0 < wall.max_y < 4.5):
            raise ValueError(f"{name} elevation range is not credible")


def validate(root: Path = OUTPUT) -> tuple[int, int, int, int]:
    """Validate fixture structure, geometry, materials, and textures.

    ``root`` is injectable so adversarial tests can mutate a temporary copy
    without touching the checked-in fixture.
    """

    obj_path, mtl_path, texture_paths = fixture_paths(root)
    if not obj_path.is_file() or not mtl_path.is_file():
        raise FileNotFoundError("OBJ/MTL fixture is missing; run the generator first")
    obj_bytes = obj_path.stat().st_size
    if obj_bytes < 50_000_000:
        raise ValueError(f"OBJ is {obj_bytes} bytes; expected at least 50,000,000 bytes")

    materials = parse_mtl(mtl_path)
    for required_material, expected_texture in REQUIRED_MATERIAL_TEXTURES.items():
        block = materials.get(required_material)
        if block is None:
            raise ValueError(f"Required material block is missing: {required_material}")
        map_reference = block.get("map_Kd")
        if map_reference is None:
            raise ValueError(f"Required material has no map_Kd: {required_material}")
        resolve_texture_reference(map_reference, obj_path.parent, expected_texture)
    for block in materials.values():
        map_reference = block.get("map_Kd")
        if map_reference is not None:
            resolve_texture_reference(map_reference, obj_path.parent)

    positions: list[tuple[float, float, float]] = [(0.0, 0.0, 0.0)]
    texcoords: list[tuple[float, float]] = [(0.0, 0.0)]
    normals: list[tuple[float, float, float]] = [(0.0, 0.0, 0.0)]
    groups: dict[str, GroupStats] = {}
    active_group: GroupStats | None = None
    active_material: str | None = None
    mtllib_seen = False
    for line_number, raw_line in enumerate(obj_path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        tokens = line.split()
        keyword = tokens[0]
        if keyword == "mtllib":
            if len(tokens) != 2 or tokens[1] != mtl_path.name:
                raise ValueError(f"OBJ references an unexpected MTL at line {line_number}")
            mtllib_seen = True
        elif keyword == "v":
            if len(tokens) != 4:
                raise ValueError(f"Malformed vertex at line {line_number}")
            positions.append(tuple(_parse_float(value, obj_path, line_number) for value in tokens[1:]))
        elif keyword == "vt":
            if len(tokens) < 3 or len(tokens) > 4:
                raise ValueError(f"Malformed texture coordinate at line {line_number}")
            texcoords.append(tuple(_parse_float(value, obj_path, line_number) for value in tokens[1:3]))
        elif keyword == "vn":
            if len(tokens) != 4:
                raise ValueError(f"Malformed normal at line {line_number}")
            normals.append(tuple(_parse_float(value, obj_path, line_number) for value in tokens[1:]))
        elif keyword == "g":
            if len(tokens) != 2 or not tokens[1]:
                raise ValueError(f"Malformed group declaration at line {line_number}")
            if tokens[1] in groups:
                raise ValueError(f"Duplicate group declaration at line {line_number}: {tokens[1]}")
            active_group = GroupStats(tokens[1])
            groups[tokens[1]] = active_group
            active_material = None
        elif keyword == "usemtl":
            if len(tokens) != 2 or not tokens[1]:
                raise ValueError(f"Malformed material declaration at line {line_number}")
            active_material = tokens[1]
            if active_group is not None:
                if active_group.material is not None and active_group.material != active_material:
                    raise ValueError(f"Group {active_group.name} changes material at line {line_number}")
                active_group.material = active_material
        elif keyword == "f":
            if active_group is None or active_material is None:
                raise ValueError(f"Face is missing group/material context at line {line_number}")
            if len(tokens) != 4:
                raise ValueError(f"Fixture contains a non-triangular face at line {line_number}")
            triangle: list[tuple[float, float, float]] = []
            for corner in tokens[1:]:
                parts = corner.split("/")
                if len(parts) != 3 or any(not part for part in parts):
                    raise ValueError(f"Face corner is not v/vt/vn at line {line_number}: {corner}")
                try:
                    position_index, uv_index, normal_index = (int(part) for part in parts)
                except ValueError as error:
                    raise ValueError(f"Face index is not an integer at line {line_number}: {corner}") from error
                if not (1 <= position_index < len(positions)):
                    raise ValueError(f"Face position index is out of range at line {line_number}: {corner}")
                if not (1 <= uv_index < len(texcoords)):
                    raise ValueError(f"Face UV index is out of range at line {line_number}: {corner}")
                if not (1 <= normal_index < len(normals)):
                    raise ValueError(f"Face normal index is out of range at line {line_number}: {corner}")
                triangle.append(positions[position_index])
            triangle_tuple = tuple(triangle)
            if _triangle_area_squared(triangle_tuple) <= 1.0e-12:
                raise ValueError(f"Degenerate zero-area triangle at line {line_number}")
            active_group.update(triangle_tuple)

    if not mtllib_seen:
        raise ValueError("OBJ is not linked to the expected MTL")
    counts = (len(positions) - 1, len(texcoords) - 1, len(normals) - 1, sum(group.faces for group in groups.values()))
    if counts != EXPECTED_COUNTS:
        raise ValueError(f"Fixture counts changed unexpectedly: got {counts}, expected {EXPECTED_COUNTS}")
    if counts[3] < 500_000:
        raise ValueError(f"OBJ has {counts[3]} triangles; expected at least 500,000")
    if set(materials) < {"Ground", "Roof", "Wall"}:
        raise ValueError("MTL does not contain Ground, Roof, and Wall material blocks")
    for group in groups.values():
        if group.material not in materials:
            raise ValueError(f"Group {group.name} references unknown material {group.material!r}")
    if set(groups) != set(EXPECTED_GROUP_MATERIALS):
        raise ValueError(f"OBJ groups do not match the expected house surfaces: {sorted(groups)}")
    if any(group.material != EXPECTED_GROUP_MATERIALS[group.name] for group in groups.values()):
        raise ValueError("OBJ groups do not map to the expected Ground/Roof/Wall materials")
    _validate_group_shapes(groups)

    all_vertices = positions[1:]
    min_x, max_x = min(vertex[0] for vertex in all_vertices), max(vertex[0] for vertex in all_vertices)
    min_y, max_y = min(vertex[1] for vertex in all_vertices), max(vertex[1] for vertex in all_vertices)
    min_z, max_z = min(vertex[2] for vertex in all_vertices), max(vertex[2] for vertex in all_vertices)
    if not (45.0 <= max_x - min_x <= 55.0 and 35.0 <= max_z - min_z <= 45.0):
        raise ValueError("Overall model bounds are not a credible house-and-ground range")
    if not (min_x < -24.0 and max_x > 24.0 and min_z < -19.0 and max_z > 19.0):
        raise ValueError("Overall model bounds do not include the expected ground extents")
    if not (6.5 <= max_y - min_y <= 8.5 and min_y < 0.0 < max_y):
        raise ValueError("Overall model elevation range is degenerate or implausible")

    for texture in texture_paths.values():
        width, height = jpeg_dimensions(texture)
        if width < 1 or height < 1:
            raise ValueError(f"Texture has invalid dimensions: {texture}")
        _validate_artifact_hash(texture, EXPECTED_ARTIFACT_SHA256[texture.name])
    _validate_artifact_hash(mtl_path, EXPECTED_ARTIFACT_SHA256[mtl_path.name])
    _validate_artifact_hash(obj_path, EXPECTED_ARTIFACT_SHA256[obj_path.name])
    return counts


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--validate", action="store_true", help="validate the checked-in fixture without regenerating it")
    args = parser.parse_args()
    stats = validate() if args.validate else generate()
    print(
        f"synthetic WebODM fixture: vertices={stats[0]} texcoords={stats[1]} "
        f"normals={stats[2]} triangles={stats[3]} obj_bytes={OBJ_PATH.stat().st_size}"
    )


if __name__ == "__main__":
    main()
